name: .NET Core

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build 
      run: dotnet build --configuration Release
    - name: Test C#
      run: dotnet test ./tst/BitHack.CSharp.Tests/BitHack.CSharp.Tests.csproj
    - name: Test F#
      run: dotnet test ./tst/BitHack.Tests/BitHack.Tests.fsproj
    - name: Build C# NuGet Package
      run: 
        dotnet pack ./src/BitHack.CSharp/BitHack.CSharp.csproj --configuration Release -o ./nuget
    - name: Build F# Nuget Package
      run:
        dotnet pack ./src/BitHack/BitHack.fsproj --configuration Release -o ./nuget
    - name: Deploy NuGet Packages
      run:
        dotnet nuget push /home/runner/work/SFX.BitHack/SFX.BitHack/nuget/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
